# Generated by Django 5.0.6 on 2026-06-04 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('grade', models.CharField(default='', max_length=2)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='domains.domain')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('check_key', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=16)),
                ('severity', models.CharField(max_length=16)),
                ('score_impact', models.IntegerField(default=0)),
                ('observed_value', models.TextField(blank=True, default='')),
                ('remediation', models.TextField(blank=True, default='')),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scans.scan')),
            ],
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['domain', '-created_at'], name='scans_scan_domain__913461_idx'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['scan', 'category'], name='scans_check_scan_id_2869ce_idx'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['scan', 'status'], name='scans_check_scan_id_5856f4_idx'),
        ),
    ]
