# Generated by Django 5.0.6 on 2026-06-04 14:43

import apps.public.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('grade', models.CharField(default='', max_length=2)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('share_token', models.CharField(default=apps.public.models._token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['hostname'], name='public_gues_hostnam_62a786_idx'), models.Index(fields=['-created_at'], name='public_gues_created_e091b6_idx'), models.Index(fields=['ip_address', '-created_at'], name='public_gues_ip_addr_605429_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuestCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('check_key', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=16)),
                ('severity', models.CharField(max_length=16)),
                ('score_impact', models.IntegerField(default=0)),
                ('observed_value', models.TextField(blank=True, default='')),
                ('remediation', models.TextField(blank=True, default='')),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='public.guestscan')),
            ],
        ),
    ]
