# Generated by Django 5.0.6 on 2026-06-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
    ]
