# Generated by Django 5.0.6 on 2026-06-04 14:43

import apps.domains.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(default=apps.domains.models._token, max_length=64)),
                ('verification_method', models.CharField(choices=[('dns_txt', 'DNS TXT'), ('well_known', '/.well-known file')], default='dns_txt', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('owner', 'hostname'), name='uniq_owner_hostname'),
        ),
    ]
